;; DxWrapper v1.8.8600.25
;; https://github.com/elishacloud/dxwrapper

[General]
RealDllPath = AUTO
WrapperMode = AUTO
DisableLogging = 1

[Plugins]
LoadPlugins = 1
LoadFromScriptsOnly = 1

[Compatibility]
EnableD3d9Wrapper = 1
